name: CI

on:
  workflow_dispatch:
  push:
    branches: [ test/main ]
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        linter:
          - golangci-lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Run linter
        run: nix run .#lint-${{ matrix.linter }}

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package:
          - nix-snapshotter
          - image-hello
          - image-redis
          - image-redisWithShell
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Build package
        run: nix build .#${{ matrix.package }}

  integration-test:
    strategy:
      matrix:
        test:
          - snapshotter
          - kubernetes
    runs-on: ubuntu-22.04
    needs: [lint, build]
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          enable-kvm: true
      - name: Build snapshotter
        run: nix build
      - name: Run integration tests
        run: nix run -L .#test-${{ matrix.test }}
